name: Deploy to Hugging Face Spaces
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with: python-version: '3.11'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Deploy to Spaces
      run: |
        pip install huggingface_hub
        huggingface-cli login --token ${{ secrets.HF_API_KEY }}
        hugo deploy # ou scripts spécifiques pour HF Spaces
